### ISSUE TITLE
Observations post-linting

### ISSUE THREAD

**Issue by aendrew** [ft-interactive/visual-vocabulary-templates#10]
In #8, I linted all the major files in the project, which flagged up a few things for me:

- *Using globals for everything feels kind of haphazard.* In #8, I got past linter warnings without having to specify a ton of `globals` ESlint properties by using the following construct:

```js
const {
  d3,
  gChartframe
} = window;
```

...Which creates a reference to D3 from the `window` global object so it can be used in local scope. I'm really not sure if this is ultimately better than putting the following at the top of each file:
```
/* global d3,  gChartframe */
```

Regardless, this reliance on globals means we lose a lot of beneficial tooling (confusing for ESLint, makes life difficult for things like TernJS). 

- *Not using modules means we need to put `'use strict';` in the global scope.* It's generally a good idea to write code in strict mode as it flags up bugs faster in development and provides better error reporting when trying to solve weird JS issues. If we used some sort of module format, strict mode is implicit and we wouldn't need to specify it.

- *We should standardise spellings for some things*. I mention this particularly in reference to `g-chartcolour` — even though I personally prefer British spellings for practically everything, in code I'm fairly adamant that it's a sound idea to standardise on American spellings for variable, function and package naming. This is purely due to the fact that programming languages are standardised on American spelling and the productivity lost by the cognitive dissonance caused by trying to remember whether something has a "u" in it or not ultimately builds up really quickly. 

- *Legend should be a package*. It's shared across practically every example so should be in common code.

**Comment by sdbernard** [comment]
Yup the legend is defo going to be a package, the version in the column grouped/timeline was only written yesterday to be able to work across most chart types. Now it allows you to specify line, rect or circle geometry as the marker next to the label

**Comment by sdbernard** [comment]
The styles that are common to all charts should also be packaged, mainly stroke widths, axis font sizes and styles

**Comment by aendrew** [comment]
@sdbernard Yeah, I just noticed the CircleCI notification for g-legend — nicely done! :+1: 

While on the topic of common code — any thoughts as to what the separation of concerns is between the code in `index.html` and `<chartType>.js`? The code in the HTML file sometimes is longer than the JS file, which doesn't make a lot of sense IMO — the top-level API is generally that exposed to the HTML file, with more rudimentary concerns handled by dependencies pulled in (In this case that would mean specifying titles, chart dimensions, etc., maybe data loading). I may simply be missing something, however.

**Comment by aendrew** [comment]
This is really outdated, and all the points above have been merged. Closing as such.
